---
output:
  html_document:
---


## Chapter 4 
1. Advertising today is driven by the mass amounts of personal data collected from various sources. Do you feel comfortable using “free services” (i.e. Facebook, Google) where payment is your data?  If not, are you willing to pay for services instead? 
1. Do you think personalized advertising is useful in online retail? Do you feel comfortable giving away personal data to receive a personalized experienced? (i.e. Amazon) 
1. An algorithm itself is neither good nor bad – it is how it is written and implemented.  Is there a way to monetize public health marketing for companies? (i.e. Amazon using its algorithm to find those vulnerable and market them appropriate services such as mental health care, unemployment benefits, and other resources). 
1. Are there any benefits from for-profit colleges? Should the federal government stop allowing student loads for these institutions?  


Interested in learning more about for-profit colleges? Check out <a href="https://thenewpress.com/books/lower-ed" target = "_blank"> Lower Ed by Tressie McMillan Cottom<a/>^[Available for purchase at [Bookends and Beginnings](https://www.bookendsandbeginnings.com/book/9781620974384)] , recommended by Abby Smith.  Also check out Frontline's <a href = "https://www.pbs.org/video/frontline-subprime-education/" target = "_blank" > Subprime Education </a>  from 2010.   




