---
output:
  html_document:
---


## Chapter 6
<ol>
<li> Should personality test be used in any capacity in a work environment?  Why or why not?  
<small>
  <ul>
    <li> “… if we define the goal as a happier worker, personality tests might end up being a useful tool.” (Ch 6, p 109)  </li>
    <li> “The primary purpose of the test is not to find the best employee.  It’s to exclude as many people as possible as cheaply as possible” (Ch 6, p 109)  </li>
    <li> “It’s doing its job – even if it misses out on potential stars” (Ch 6, p 111) </li> 
    </ul>
  </small>
</li> 
<li> In Investment Banking and Consulting, interviewees are asks a variety of questions to gauge their ability for critical thinking on the spot as well as their knowledge of the field.  Many programing and data science jobs require some sort of take-home coding assessment or project.  These ‘tests’ are not done blindly – they are done after a resume is picked from the pile and the individual is known. Is it possible to implement some form of a ‘blind audition’ for these positions? What about for the majority of jobs?
</li>
</ol>






