---
output:
  html_document:
---


## Chapter 9

<ol>
<li> A common issue with insurance is confusing causation with correlation (i.e. people of color have lower life expectancy and saying that is due to race rather than a product of poverty and injustice).  This is a basic statistical topic that is (or at least should be) taught in intro-level classes.  Why do you think it is so difficult for people to understand the difference between causation and correlation?  How can we improve this in science and society?
</li>
<li>
As more data are available, insurers are able to put people into smaller and smaller groups with very targeted pricing.  Discuss the following issues and what you would do to alleviate the negative impact: 
<ul>
<li> <b> Privacy: </b> use of personal data (driving data, BMI, cholesterol and other health data) </li>
<li> <b> Transparency: </b> people often don’t know what ‘group’ they are in and how that affect pricing </li>
<li> <b> Choice: </b>  requirement to participate in programs (tracking driving data or wellness programs) </li> 
</ul>
</li>
</ol>




